

export const rows = [
    {
      id: 1,
      lastName: "Snow",
      firstName: "Jon",
      login: "Papacita",
      email: "1@mail.ru",
      test: "testField",
      status: "Active",
    },
    {
      id: 2,
      lastName: "Lannister",
      firstName: "Cersei",
      login: "Psina",
      email: "2@mail.ru",
      test: "testField",
      status: "Active",
    },
    {
      id: 3,
      lastName: "Lannister",
      firstName: "Jaime",
      login: "Bitum",
      email: "3@mail.ru",
      test: "testField",
      status: "Inactive",
    },
    {
      id: 4,
      lastName: "Stark",
      firstName: "Arya",
      login: "Kolyan",
      email: "4@mail.ru",
      test: "testField",
      status: "Active",
    },
    {
      id: 5,
      lastName: "Targaryen",
      firstName: "Daenerys",
      login: "Mom",
      email: "5@mail.ru",
      test: "testField",
      status: "Inactive",
    },
    {
      id: 6,
      lastName: "Melisandre",
      firstName: null,
      login: "Shtanga",
      email: "6@mail.ru",
      test: "testField",
      status: "Active",
    },
    {
      id: 7,
      lastName: "Clifford",
      firstName: "Ferrara",
      login: "Qwerty",
      email: "7@mail.ru",
      test: "testField",
      status: "Active",
    },
    {
      id: 8,
      lastName: "Frances",
      firstName: "Rossini",
      login: "Jeep",
      email: "8@mail.ru",
      test: "testField",
      status: "Inactive",
    },
    {
      id: 9,
      lastName: "Roxie",
      firstName: "Harvey",
      login: "Pes",
      email: "9@mail.ru",
      test: "testField",
      status: "Active",
    },
  ];